# Generated by Django 5.2.10 on 2026-05-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd_mapping', '0002_alter_requirement_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='manual_status',
            field=models.CharField(blank=True, choices=[('HOT', 'Hot (0-4 hours)'), ('WARM', 'Warm (4-24 hours)'), ('COLD', 'Cold (24+ hours)')], help_text='If set, this overrides auto status', max_length=10, null=True, verbose_name='Manually Set Status'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='manual_status_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Manual Status Update Time'),
        ),
    ]
