# Generated by Django 5.2.10 on 2026-05-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd_mapping', '0003_requirement_manual_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='vendor_budget_range',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vendor Budget Range'),
        ),
    ]
